// config.js - Central configuration for dynamic content
export const SITE_CONFIG = {
  title: "Vikram Prajapat - Creative Portfolio",
  description:
    "Video editor & motion designer crafting impactful digital experiences",
  author: "Vikram Prajapat",
  email: "hello@vikram.com",
  phone: "+1 (555) 123-4567",
  location: "Based in Creative City",
  socialLinks: {
    youtube: "#",
    linkedin: "#",
    instagram: "#",
    twitter: "#",
  },
  features: {
    darkMode: true,
    animations: true,
    contactForm: true,
  },
};

export const PROJECT_CATEGORIES = [
  "all",
  "animations",
  "podcast",
  "videos",
  "reels",
  "thumbnail",
];

export const SKILLS = [
  { name: "Video Editing", level: 95 },
  { name: "Motion Graphics", level: 90 },
  { name: "Visual Effects", level: 85 },
  { name: "Sound Design", level: 80 },
];

// Dynamic content that can be updated
export const DYNAMIC_CONTENT = {
  stats: {
    projects: 250,
    clients: 100,
    views: 5000000,
    awards: 15,
  },
  availability: true,
  rotatingTexts: [
    "Visual Magic",
    "Engaging Content",
    "Creative Solutions",
    "Digital Experiences",
  ],
};

// Export all projects data
export const allProjects = [
  {
    id: 1,
    title: "Motion Graphics Showreel",
    category: "animations",
    views: "125K",
    likes: "8.5K",
    duration: "2:30",
    color: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "A stunning showcase of motion graphics and visual effects",
    tags: ["After Effects", "Cinema 4D", "Visual Effects"],
    projectLink: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Tech Podcast Series",
    category: "podcast",
    views: "89K",
    likes: "6.2K",
    duration: "45:00",
    color: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Professional podcast editing for tech industry leaders",
    tags: ["Audition", "Sound Design", "Mixing"],
    projectLink: "#",
    featured: true,
  },
  {
    id: 3,
    title: "Brand Documentary",
    category: "videos",
    views: "210K",
    likes: "12.5K",
    duration: "15:20",
    color: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)",
    description: "Long-form brand storytelling documentary",
    tags: ["Premiere Pro", "Color Grading", "Storytelling"],
    projectLink: "#",
    featured: false,
  },
  {
    id: 4,
    title: "Social Media Reels",
    category: "reels",
    views: "350K",
    likes: "25K",
    duration: "0:45",
    color: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)",
    description: "Viral social media content series",
    tags: ["Mobile Editing", "Trend Analysis", "Engagement"],
    projectLink: "#",
    featured: true,
  },
  {
    id: 5,
    title: "YouTube Thumbnail Pack",
    category: "thumbnail",
    views: "75K",
    likes: "4.2K",
    duration: "N/A",
    color: "linear-gradient(135deg, #fa709a 0%, #fee140 100%)",
    description: "Custom thumbnail designs for YouTube creators",
    tags: ["Photoshop", "Illustrator", "Design"],
    projectLink: "#",
    featured: false,
  },
  {
    id: 6,
    title: "Product Launch Video",
    category: "videos",
    views: "180K",
    likes: "9.8K",
    duration: "3:15",
    color: "linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)",
    description: "Dynamic product launch campaign video",
    tags: ["Motion Graphics", "Sound Design", "Marketing"],
    projectLink: "#",
    featured: true,
  },
  {
    id: 7,
    title: "Corporate Training Series",
    category: "videos",
    views: "95K",
    likes: "5.2K",
    duration: "12:30",
    color: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    description: "Professional corporate training video series",
    tags: ["Scripting", "Animation", "Education"],
    projectLink: "#",
    featured: false,
  },
  {
    id: 8,
    title: "Music Video Production",
    category: "animations",
    views: "420K",
    likes: "31K",
    duration: "4:15",
    color: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)",
    description: "Creative music video with visual effects",
    tags: ["VFX", "Color Grading", "Audio Sync"],
    projectLink: "#",
    featured: true,
  },
];
